name: wuchers_garage
description: wuchers garage internal application.

publish_to: 'none'

version: 1.3.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^0.3.2
  font_awesome_flutter: ^9.1.0
  avatar_glow: ^2.0.2
  flutter_login: ^2.2.1
  provider: ^5.0.0
  image_picker: ^0.8.4
  firebase_auth: ^1.4.0
  firebase_core: ^1.3.0
  flutter_clean_calendar: ^1.1.0
  flutter_slidable: ^0.6.0
  cloud_firestore: ^2.4.0
  file_picker: ^4.0.0
  open_file: ^3.2.1
  intl: ^0.17.0
  http: ^0.13.3
  pdf: ^3.6.0
  path_provider: ^2.0.4
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
